### PR TITLE
XIVY-6292 Enable resources plugin per default in lifecycle

### PR DESCRIPTION
**Pull request by ivy-lli**
image

### CODE REVIEW

**Comment by ivy-rew** [comment]
will we get the above warning, if no "resources" section is defind in the pom.xml?

**Comment by ivy-lli** [comment]
Yes...
grafik
Can we define somehow this encoding within our plugin?

**Comment by ivy-lli** [comment]
Maybe set the property to the effective pom? https://maven.apache.org/plugins/maven-resources-plugin/examples/encoding.html

**Comment by ivy-rew** [comment]
I don't know how, but yes I'd assume that we can supply such defaults, similar as we contribute our lifecycle.
At any rate, our default created POMs should not produce such warnings that threaten inexperienced users.

**Comment by ivy-rew** [comment]
In theory we can configure everything that exists as component: (as we do the declare our lifecycle):
mavenComponents
But I can't quickly identify the component that defines the the default encoding property.

Also possible would be to supply setup a goal, that just lives in order to manipulate properties. I think our test-properties goal is one of these. Likewise we could override the source-encoding properties with an early running goal of us.

And of course the other valid solution would be, to change our pom.xml creation in the designer, to include the utf8 encoding declaration by default.

**Comment by ivy-lli** [comment]
I've add an additional mojo entry (same as it is done for the integration test surefire stuff).
If you don't define anything in your project:
grafik
If you define it in your project:
grafik

**Review by ivy-rew — APPROVED** [review]

**Review by ivy-rew — APPROVED** [review]

**Pull request merged**
