### PR TITLE
fix: only do releases on user triggered pipelines

### PR DESCRIPTION
**Pull request by ivy-rew**

### CODE REVIEW

**Comment by ivy-rew** [comment]
alternatively we could way for user feedback to actually do the release ... just as we do on the real product release branch.
feel free to share your preference @alexsuter

**Comment by alexsuter** [comment]
I would prefer a release build which is only triggered manually, as we do it in webtester or in all market products.
But good for me!

**Review by alexsuter — APPROVED** [review]

**Comment by ivy-rew** [comment]
do you know where this logic is to only use manual runs? I can't find anything about it in the build pipeline
https://github.com/axonivy/web-tester/blob/master/build/release/Jenkinsfile
 
it seems like the project-build-plugin has the same setup. still the build was triggered by a timer last night.
So I can't see why this didn't happen earlier :thinking: 
timed-build

**Comment by alexsuter** [comment]
No I don't know why. This should not happen. @ivy-cst Do you think this could be a bug in jenkins after jenkins update? Do you have upgraded jenkins yesterday?

**Comment by ivy-cst** [comment]
Because @ivy-rew has replayed with a midnight trigger: https://jenkins.ivyteam.io/job/project-build-plugin_release/job/release%252F10.0/23/replay/

**Comment by ivy-rew** [comment]
> Because @ivy-rew has replayed with a midnight trigger: https://jenkins.ivyteam.io/job/project-build-plugin_release/job/release%252F10.0/23/replay/diff

ahh damn it. never thought that this results in such a strange way. 
just did a re-launch with the "non-release" pipeline.
but thanks for making this strange happening reasonable :)

**Comment by ivy-cst** [comment]
> > Because @ivy-rew has replayed with a midnight trigger: https://jenkins.ivyteam.io/job/project-build-plugin_release/job/release%252F10.0/23/replay/diff
> 
> ahh damn it. never thought that this leads to such a strange behavior. I just did a re-launch, with a custom script yesterday, with the "non-release" pipeline to see if it works. That this custom manual launch will be re-triggered in the night wasn't anything I'd imagined. but thanks for making this strange happening reasonable :)

Always the last pipeline execution counts for triggers and paramters and that stuff ...

**Pull request merged**
